sudo: true
language: android
jdk: oraclejdk8
android:
  components:
    - tools
    - tools
    - android-28
    - android-24
    - sys-img-armeabi-v7a-android-24
    - build-tools-28.0.3
    - platform-tools
    - extra-google-m2repository
before_script:
  - echo no | android create avd --force -n test -t android-24 --abi armeabi-v7a
  - emulator -avd test -skin WXGA720 -no-audio -no-window &
  - android-wait-for-emulator
  - sleep 60
  - adb shell input keyevent 82
script: ./gradlew clean connectedAndroidTest
